
name: Api Auto Build
on:
  schedule:
  - cron: '0 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger our build webhook on Netlify
      run: curl -s -X POST "https://api.netlify.com/build_hooks/5f9a36a5efcb988504c42d04"
      # env:
      #   TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK }}